# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm install

    - name: Set environment variables
      run: |
        echo "FIREBASE_API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV
        echo "AUTH_DOMAIN=${{ secrets.AUTH_DOMAIN }}" >> $GITHUB_ENV
        echo "FIREBASE_DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
        echo "FIREBASE_PROJECT_ID=${{ secrets.PROJECT_ID }}" >> $GITHUB_ENV
        echo "FIREBASE_STORAGE_BUCKET=${{ secrets.STORAGE_BUCKET }}" >> $GITHUB_ENV
        echo "FIREBASE_MESSAGING_SENDER_ID=${{ secrets.MESSAGING_SENDER_ID }}" >> $GITHUB_ENV
        echo "FIREBASE_APP_ID=${{ secrets.APP_ID }}" >> $GITHUB_ENV
        node set-env.js

    - name: Build the application
      run: npm run build --prod 2> >(grep -v "WARNING" >&2)
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/brain-ridge/browser
